version: '3.8'

services:
  redis:
    image: redis:alpine  # Use the official Redis image
    ports:
      - "6380:6380"   # Expose Redis port

  djweb:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./_prj/.env
    ports:
      - 8001:8000
    depends_on:
      - redis

  celery:
    container_name: celery
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis