version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:alpine  # Use the official Redis image
    ports:
      - 6379:6379   # Expose Redis port

  djweb:
    build: .
    container_name: djweb
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./_prj/.env
    ports:
      - 8001:8000
    depends_on:
      - redis

  celery:
    container_name: celery
    build: .
    command: celery --app=_prj worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis